apiVersion: v1
kind: ConfigMap
metadata:
  name: jasminegraph-config
  labels:
    application: jasminegraph
data:
  PUSHGATEWAY_ADDRESS: "${PUSHGATEWAY_ADDRESS}"
  PROMETHEUS_ADDRESS: "${PROMETHEUS_ADDRESS}"
  MAX_WORKER_COUNT: "${MAX_WORKER_COUNT}"
  auto_scaling_enabled: "true"
  scale_on_adgr: "false"
