apiVersion: v1
kind: ConfigMap
metadata:
  name: jasminegraph-config
  labels:
    application: jasminegraph
data:
  PUSHGATEWAY_ADDRESS: "${PUSHGATEWAY_ADDRESS}"
  PROMETHEUS_ADDRESS: "${PROMETHEUS_ADDRESS}"
  MAX_WORKER_COUNT: "${MAX_WORKER_COUNT}"
  AUTO_SCALING_ENABLED: "true"
  SCALE_ON_ADGR: "false"
